### ISSUE TITLE
make the new version available on fdroid

### ISSUE THREAD

**Issue by jpggithub** [estearg/android-piano#4]
Thanks for this very useful app!
Can you make the new versions available on https://f-droid.org/?
The actual version is 1.5 updated in july, 11th 2014.

**Comment by IzzySoft** [comment]
You can [find it in my repo](https://apt.izzysoft.de/fdroid/index/apk/org.esteban.piano) :wink:

**Comment by jpggithub** [comment]
Thanks but it would be nice to update your app on fdroid ;-)

**Comment by IzzySoft** [comment]
Guess you'd have to [file an issue with F-Droid](https://gitlab.com/fdroid/fdroiddata/issues) then, as they are the ones building for their repo. They could say why the app is no longer updated there and point out what's needed from @estearg's end.

**Comment by schmittlauch** [comment]
I'm glad that this app is still maintained.
According to the [F-Droid wiki page on it](https://f-droid.org/wiki/page/org.esteban.piano ) the issues with the last build were having a known security vulnerability (OpenSSL?) and using MD5 for signing the apk. (maybe also related to #5)

If these issues are solved I guess there's a point in filing an issue at f-droid.

**Comment by IzzySoft** [comment]
> I'm glad that this app is still maintained.

@schmittlauch Looks rather like it's not 😢

**Comment by estearg** [comment]
Hello.
It's abandoned.
I hope someone can take care of it.
Thank you for your interest.

**Comment by IzzySoft** [comment]
@estearg thanks for clarification! Well, nothing lasts forever… Good luck then with the projects you're currently running!
